version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Building Python app..."
      - mkdir output
      - cp -r * output/

artifacts:
  files:
    - '**/*'
  base-directory: output
