version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt || true  # Skip if not present

  build:
    commands:
      - echo "Build phase started."
      - echo "No build needed for static Python files."
      - python app.py

artifacts:
  files:
    - '**/*'
    - '!buildspec.yml'  # Optional: don't include the buildspec in deployment
